version: '3.8'

services:
  stock-split-checker:
    build: .
    container_name: stock-split-checker
    restart: unless-stopped
    volumes:
      # Mount .env file (create this file with your credentials)
      - ./.env:/app/.env
      # Mount logs directory to persist logs and last_run.txt
      - ./logs:/app/logs
      # Mount stock split checker log file
      - ./logs/stock_split_checker.log:/app/stock_split_checker.log
      # Mount last_run.txt to persist last run info
      - ./logs/last_run.txt:/app/logs/last_run.txt
    environment:
      - TZ=America/Denver  # Mountain Time (MST/MDT with daylight saving)
    # Optional: if you want to access the container
    # ports:
    #   - "8080:8080"
